server:
  port: 3344
spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/Awei73807/springcloud-config.git #https的路径

#通过config-server可以连接到git 访问其中的资源以及配置